version: "3.1"

services:

    db:
        image: mysql
        build:
            context: .
            args:
                RAM_AMOUNT: ${RAM_AMOUNT}
        volumes:
            - .server-data:/etc/mysql/
        ports:
            - 3307:3306
        container_name: ${CONTAINER_NAME}
        command: --default-authentication-plugin=mysql_native_password
	restart: always
	environment:
		MYSQL_ROOT_PASSWORD: admin1234

    adminer:
        image: adminer
	restart: always
	ports:
            - 8083:80
		
volumes:
    server-data:

# docker-compose up --build