version: "3"

services:
    centos-lab:
        build:
            context: .
            args:
                RAM_AMOUNT: ${RAM_AMOUNT}
        volumes:
            - .server-conf:/etc/httpd/conf.d
            - .server-data:/var/www/html/
        ports:
            - 49794:22
            - 8084:80
        container_name: ${CONTAINER_NAME}
        networks:
            - lab_network

volumes:
    server-conf:
    server-data:

networks:
    lab_network: