version: "3"

services:
    apacheTest01:
        build:
            context: .
            args:
                RAM_AMOUNT: ${RAM_AMOUNT}
        volumes:
            - .server-data:/var/www/
            - .ssl-data:/etc/apache2/
        ports:
            - 81:80
            - 444:443
        container_name: ${CONTAINER_NAME}

volumes:
    server-data: