FROM node:9-slim
WORKDIR /app
COPY package.json ./app
RUN npm install


# docker-compose up
# =============== [Nginx Proxy user] =========================
# http://localhost:81
# admin@example.com : changeme : nextcloud-app
# Administrator: admin : admin@test.local : admin123
# ============================================================