version: "3"

services:
    xamptest01:
        build:
            context: .
            args:
                RAM_AMOUNT: ${RAM_AMOUNT}
        volumes:
            - .server-conf:/opt/lampp/apache2/conf.d
            - .server-data:/opt/lampp/htdocs/
        ports:
            - 49791:22
            - 8084:80
        container_name: ${CONTAINER_NAME}

volumes:
    server-conf:
    server-data:

# docker-compose up --build