version: '3'

networks:
    laravelNT:

services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx-laravel-lab
        ports:
            - "8088:80"
        volumes:
            - ./nginx-data:/var/www/html
            - ./nginxConf/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - mysql
        networks:
            - laravelNT

    mysql:
        image: mysql:5.7.22
        container_name: mysql-laravel-lab
        restart: unless-stopped
        tty: true
        ports:
            - "4306:3306"
        volumes:
            - ./mysql-data:/var/lib/mysql
        environment:
            MYSQL_DATABASE: laravelLabDB
            MYSQL_USER: laravelLab
            MYSQL_PASSWORD: Admin1234
            MYSQL_ROOT_PASSWORD: Admin1234
            SERVICE_TAGS: laravelDevTag
            SERVICE_NAME: laravelMysqlServiceName
        networks:
            - laravelNT

    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php-laravel-lab
        volumes:
            - ./nginx-data:/var/www/html
        ports:
            - "9000:9000"
        networks:
            - laravelNT