version: "2.1"
services:
    code-server:
        image: lscr.io/linuxserver/code-server:latest
        container_name: vscode-server
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Canada/Central
            - PASSWORD=Admin123 #optional
            - HASHED_PASSWORD= #optional
            - SUDO_PASSWORD=Admin123 #optional
            - SUDO_PASSWORD_HASH= #optional
            - PROXY_DOMAIN=vscode.test.local #optional
            - DEFAULT_WORKSPACE=/config/workspace #optional
        volumes:
            - /path/to/appdata/config:/config
        ports:
            - 8443:8443
        restart: unless-stopped

# docker-compose up --build