version: "3"
services:
    filebrowser:
        image: filebrowser/filebrowser
        container_name: file-browser
        user: 1001:1000
        ports:
            - 8081:80
        volumes:
            - .serveradmin/VerDocumentos:/srv
            - .serveradmin/filebrowser/filebrowser.db:/database.db
        restart: unless-stopped
        security_opt:
            - no-new-privileges:true