version: "3"

services:
    minecraft-server:
        build:
            context: .
            args:
                RAM_AMOUNT: ${RAM_AMOUNT}
        volumes:
            - .server-data:/server
        ports:
            - 25567:25565
            - 25577:25575
        container_name: ${CONTAINER_NAME}

volumes:
    server-data:

# docker-compose up --build