version: '3'

services:
  nodejs-app:
    container_name: nodejs-app
    restart: unless-stopped
    build:
      context: .
    ports:
      - "3001:3000"
    volumes:
      - ./app:/app

# Errores
# 1) Error: Cannot find module 'express'

# Limpiar
# docker container prune
# docker image prune
# docker system prune
# docker container prune -f && docker image prune -f && docker system prune -f

# Build the Docker Image:
# docker-compose up --build
